### ISSUE TITLE
LICENSE problem

### ISSUE THREAD

**Issue by Ishotihadus** [K0lb3/texture2ddecoder#9]
I'm the author of the open-source library [mikunyan](https://github.com/Ishotihadus/mikunyan), which is licensed under [MIT License](https://github.com/Ishotihadus/mikunyan/blob/master/LICENSE.txt).

Some of your codes are derived from my project, such as:
- https://github.com/K0lb3/texture2ddecoder/blob/master/src/Texture2DDecoder/etc.cpp
- https://github.com/K0lb3/texture2ddecoder/blob/master/src/Texture2DDecoder/astc.cpp

c.f. my own code:
- https://github.com/Ishotihadus/mikunyan/blob/master/ext/decoders/native/etc.c
- https://github.com/Ishotihadus/mikunyan/blob/master/ext/decoders/native/astc.c

Could you review these source codes, follow my license text, and resolve license problem?

Note that Perfare has pointed out my work in [his readme text](https://github.com/Perfare/AssetStudio).

**Comment by K0lb3** [comment]
Sorry,
when I created this module I had no clue about licensing itself,
and I forgot to copy the license section I added for the Rust port of this module.

**Comment by Ishotihadus** [comment]
Nice update!
